spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cnpj_db
    username: cnpj_user
    password: postgresql
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
integration:
  rf-cnpj-path: https://arquivos.receitafederal.gov.br/